### ISSUE TITLE
Compiler finding not existing bugs?

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-python#4]
<img width="1440" alt="screen shot 2017-04-22 at 11 09 30 pm" src="https://cloud.githubusercontent.com/assets/689092/25308255/cf07c336-27b0-11e7-9fa0-2f23393f33b8.png">

**Comment by VISTALL** [comment]
Please show null error

**Comment by winxalex** [comment]
`null
java.lang.NullPointerException
	at com.intellij.util.indexing.RebuildStatus.requestRebuild(RebuildStatus.java:45)
	at com.intellij.util.indexing.FileBasedIndexImpl.requestRebuild(FileBasedIndexImpl.java:1353)
	at com.intellij.util.indexing.FileBasedIndexImpl.scheduleRebuild(FileBasedIndexImpl.java:1090)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:847)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:915)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:889)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:753)
	at com.jetbrains.python.psi.stubs.PySetuptoolsNamespaceIndex.find(PySetuptoolsNamespaceIndex.java:119)
	at com.jetbrains.python.psi.PyUtil.isSetuptoolsNamespacePackage(PyUtil.java:1275)
	at com.jetbrains.python.psi.PyUtil.isPackage(PyUtil.java:1264)
	at com.jetbrains.python.inspections.PyProtectedMemberInspection$Visitor.isImportFromTheSamePackage(PyProtectedMemberInspection.java:113)
	at com.jetbrains.python.inspections.PyProtectedMemberInspection$Visitor.visitPyImportElement(PyProtectedMemberInspection.java:104)
	at com.jetbrains.python.psi.impl.PyImportElementImpl.acceptPyVisitor(PyImportElementImpl.java:316)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:89)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:68)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:287)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:123)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:212)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1119)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$0(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:587)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`

**Comment by VISTALL** [comment]
ty

**Comment by VISTALL** [comment]
error fixed
